# Generated by Django 5.2.11 on 2026-02-27 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employee_branch_remove_auditlog_branch_and_more'),
        ('sales', '0006_sale_seller_sale_status_alter_sale_cashier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text="Chek ma'lumotlari (items, total, etc.)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('printed', 'Chop etildi'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
